/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import Function.MysqlCon;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.DataSource;
import javax.swing.JOptionPane;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Asus
 */
public class Login_Karyawan extends javax.swing.JFrame implements Function.loginfunc {
    private final static DataSource ds = MysqlCon.getDataSource();
    /**
     * Creates new form Login_Karyawan
     */
    int mousepX;
    int mousepY;
    public Login_Karyawan() {
        initComponents();
        this.eye_invisible.setVisible(false);
        MysqlCon db = new MysqlCon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Utama = new javax.swing.JPanel();
        Panel_Atas = new javax.swing.JPanel();
        Close_window = new javax.swing.JLabel();
        Minimize_window = new javax.swing.JLabel();
        Just_Globe = new javax.swing.JLabel();
        LogLogo = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        User_Icon = new javax.swing.JLabel();
        Lock_Icon = new javax.swing.JLabel();
        Username_field = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Password_field = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        eye_visible = new javax.swing.JLabel();
        eye_invisible = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Panel_Utama.setBackground(new java.awt.Color(48, 70, 76));

        Panel_Atas.setBackground(new java.awt.Color(139, 104, 89));
        Panel_Atas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_AtasMouseDragged(evt);
            }
        });
        Panel_Atas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel_AtasMousePressed(evt);
            }
        });

        Close_window.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close_window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_close_window_30px_2.png"))); // NOI18N
        Close_window.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_windowMouseClicked(evt);
            }
        });

        Minimize_window.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimize_window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_minimize_window_30px_5.png"))); // NOI18N
        Minimize_window.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Minimize_windowMouseClicked(evt);
            }
        });

        Just_Globe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Just_Globe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_globe_30px.png"))); // NOI18N

        LogLogo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LogLogo.setForeground(new java.awt.Color(255, 255, 255));
        LogLogo.setText("LOG IN");

        javax.swing.GroupLayout Panel_AtasLayout = new javax.swing.GroupLayout(Panel_Atas);
        Panel_Atas.setLayout(Panel_AtasLayout);
        Panel_AtasLayout.setHorizontalGroup(
            Panel_AtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_AtasLayout.createSequentialGroup()
                .addComponent(Just_Globe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LogLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Minimize_window)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Close_window))
        );
        Panel_AtasLayout.setVerticalGroup(
            Panel_AtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AtasLayout.createSequentialGroup()
                .addGroup(Panel_AtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_AtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Minimize_window, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(Close_window, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(LogLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Just_Globe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnLogin.setBackground(new java.awt.Color(48, 70, 76));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin.setText("LOG IN");
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setOpaque(true);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLoginMouseReleased(evt);
            }
        });

        User_Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_person_20px.png"))); // NOI18N

        Lock_Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lock_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_lock_20px_1.png"))); // NOI18N

        Username_field.setBackground(new java.awt.Color(48, 70, 76));
        Username_field.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Username_field.setForeground(new java.awt.Color(74, 96, 102));
        Username_field.setText("Username");
        Username_field.setBorder(null);
        Username_field.setPreferredSize(new java.awt.Dimension(57, 14));
        Username_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Username_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Username_fieldFocusLost(evt);
            }
        });
        Username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_fieldActionPerformed(evt);
            }
        });

        Password_field.setBackground(new java.awt.Color(48, 70, 76));
        Password_field.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Password_field.setForeground(new java.awt.Color(74, 96, 102));
        Password_field.setText("********");
        Password_field.setBorder(null);
        Password_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Password_fieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Password_fieldFocusLost(evt);
            }
        });

        eye_visible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eye_visible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_eye_20px.png"))); // NOI18N
        eye_visible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eye_visibleMousePressed(evt);
            }
        });

        eye_invisible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eye_invisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_invisible_20px.png"))); // NOI18N
        eye_invisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eye_invisibleMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel_UtamaLayout = new javax.swing.GroupLayout(Panel_Utama);
        Panel_Utama.setLayout(Panel_UtamaLayout);
        Panel_UtamaLayout.setHorizontalGroup(
            Panel_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Atas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_UtamaLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(Panel_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lock_Icon)
                    .addComponent(User_Icon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addComponent(Username_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Password_field))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eye_invisible)
                    .addComponent(eye_visible))
                .addGap(52, 52, 52))
            .addGroup(Panel_UtamaLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        Panel_UtamaLayout.setVerticalGroup(
            Panel_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_UtamaLayout.createSequentialGroup()
                .addComponent(Panel_Atas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Panel_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_UtamaLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(User_Icon))
                    .addGroup(Panel_UtamaLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(Username_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(Panel_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Lock_Icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eye_visible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eye_invisible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Password_field))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Utama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_fieldActionPerformed

    private void Username_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_fieldFocusGained
        if(Username_field.getText().equals("Username")){
            Username_field.setText("");
            Username_field.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_Username_fieldFocusGained

    private void Username_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Username_fieldFocusLost
        if(Username_field.getText().equals("")){
            Username_field.setText("Username");
            Username_field.setForeground(new Color(74,96,102));
        }
    }//GEN-LAST:event_Username_fieldFocusLost

    private void Password_fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_fieldFocusGained
        if(Password_field.getText().equals("********")){
            Password_field.setText("");
            Password_field.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_Password_fieldFocusGained

    private void Password_fieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_fieldFocusLost
        if(Password_field.getText().equals("")){
            Password_field.setText("********");
            Password_field.setForeground(new Color(74,96,102));
        }
    }//GEN-LAST:event_Password_fieldFocusLost

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setBackground(new Color(74 ,96 ,102));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        btnLogin.setBackground(new Color(48,70,76));
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMousePressed
        btnLogin.setBackground(new Color(23,45,51));
        btnLogin.setForeground(new Color(27, 200, 4));
        btnLogin.setBorder(BorderFactory.createLineBorder(new Color(27, 200, 4)));
    }//GEN-LAST:event_btnLoginMousePressed

    private void btnLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseReleased
        btnLogin.setBackground(new Color(48,70,76));
        btnLogin.setForeground(new Color(255,255,255));
        btnLogin.setBorder(BorderFactory.createLineBorder(new Color(255,255,255)));
    }//GEN-LAST:event_btnLoginMouseReleased

    private void Minimize_windowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize_windowMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_Minimize_windowMouseClicked

    private void Close_windowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_windowMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Close_windowMouseClicked

    private void Panel_AtasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_AtasMouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        
        this.setLocation(kordinatX-mousepX, kordinatY-mousepY);
    }//GEN-LAST:event_Panel_AtasMouseDragged

    private void Panel_AtasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_AtasMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_Panel_AtasMousePressed

    private void eye_visibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_visibleMousePressed
        showpassword();
    }//GEN-LAST:event_eye_visibleMousePressed

    private void eye_invisibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye_invisibleMousePressed
        eye_visible.setVisible(true);
        eye_invisible.setVisible(false);
        Password_field.setEchoChar('*');
    }//GEN-LAST:event_eye_invisibleMousePressed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:;
        login();
    }//GEN-LAST:event_btnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close_window;
    private javax.swing.JLabel Just_Globe;
    private javax.swing.JLabel Lock_Icon;
    private javax.swing.JLabel LogLogo;
    private javax.swing.JLabel Minimize_window;
    private javax.swing.JPanel Panel_Atas;
    private javax.swing.JPanel Panel_Utama;
    private javax.swing.JPasswordField Password_field;
    private javax.swing.JLabel User_Icon;
    private javax.swing.JTextField Username_field;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel eye_invisible;
    private javax.swing.JLabel eye_visible;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void showpassword() {
        eye_invisible.setVisible(true);
        eye_visible.setVisible(false);
        Password_field.setEchoChar((char)0);
    }

    @Override
    public void login() {
       String username = Username_field.getText();
       String password = Password_field.getText();
       String sql = "SELECT * FROM user WHERE username='"+username+"' AND password='"+password+"'";
         try {
            Connection con = ds.getConnection();
            PreparedStatement statement = con.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            if(rs.next()){
                if(username.equals(rs.getString("username")) && password.equals(rs.getString("password"))){
                    JOptionPane.showMessageDialog(null, "berhasil login");
                    new Tampil_Customer().setVisible(true);
                    this.dispose();
                }
            }else{
                    JOptionPane.showMessageDialog(null, "username atau password salah");
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
    }
}

