/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;

/**
 *
 * @author Asus
 */
public class Tambah_Service extends javax.swing.JFrame {

    /**
     * Creates new form Tambah_Service
     */
    int mousepX;
    int mousepY;
    public Tambah_Service() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Label_tambah_service = new javax.swing.JLabel();
        Logo_Service = new javax.swing.JLabel();
        Close_window = new javax.swing.JLabel();
        Minimize_window = new javax.swing.JLabel();
        Label_NamaServ = new javax.swing.JLabel();
        Nama_Serv_Txt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Label_Harga = new javax.swing.JLabel();
        Harga_Serv_Txt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnAddNew = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(48, 70, 76));

        jPanel2.setBackground(new java.awt.Color(139, 104, 89));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        Label_tambah_service.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Label_tambah_service.setForeground(new java.awt.Color(255, 255, 255));
        Label_tambah_service.setText("TAMBAH SERVICE");

        Logo_Service.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo_Service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_car_service_30px.png"))); // NOI18N

        Close_window.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close_window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_close_window_30px_2.png"))); // NOI18N
        Close_window.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_windowMouseClicked(evt);
            }
        });

        Minimize_window.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimize_window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_minimize_window_30px_5.png"))); // NOI18N
        Minimize_window.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Minimize_windowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Logo_Service, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Label_tambah_service)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Minimize_window)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Close_window))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo_Service, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Label_tambah_service, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Close_window, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Minimize_window, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Label_NamaServ.setForeground(new java.awt.Color(255, 255, 255));
        Label_NamaServ.setText("Nama Service :");

        Nama_Serv_Txt.setBackground(new java.awt.Color(48, 70, 76));
        Nama_Serv_Txt.setForeground(new java.awt.Color(74, 96, 102));
        Nama_Serv_Txt.setText("Nama Service");
        Nama_Serv_Txt.setBorder(null);
        Nama_Serv_Txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Nama_Serv_TxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Nama_Serv_TxtFocusLost(evt);
            }
        });
        Nama_Serv_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_Serv_TxtActionPerformed(evt);
            }
        });

        Label_Harga.setForeground(new java.awt.Color(255, 255, 255));
        Label_Harga.setText("Harga Service :");

        Harga_Serv_Txt.setBackground(new java.awt.Color(48, 70, 76));
        Harga_Serv_Txt.setForeground(new java.awt.Color(74, 96, 102));
        Harga_Serv_Txt.setText("Harga Service");
        Harga_Serv_Txt.setBorder(null);
        Harga_Serv_Txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Harga_Serv_TxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Harga_Serv_TxtFocusLost(evt);
            }
        });
        Harga_Serv_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Harga_Serv_TxtActionPerformed(evt);
            }
        });

        btnAddNew.setBackground(new java.awt.Color(11, 203, 187));
        btnAddNew.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddNew.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_add_to_cloud_20px.png"))); // NOI18N
        btnAddNew.setText("Add New");
        btnAddNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAddNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddNew.setOpaque(true);
        btnAddNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddNewMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddNewMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddNewMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_NamaServ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Nama_Serv_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_Harga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Harga_Serv_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_NamaServ)
                    .addComponent(Nama_Serv_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Harga)
                    .addComponent(Harga_Serv_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Close_windowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_windowMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Close_windowMouseClicked

    private void Minimize_windowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize_windowMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_Minimize_windowMouseClicked

    private void Nama_Serv_TxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Nama_Serv_TxtFocusGained
        if(Nama_Serv_Txt.getText().equals("Nama Service")){
            Nama_Serv_Txt.setText("");
            Nama_Serv_Txt.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_Nama_Serv_TxtFocusGained

    private void Nama_Serv_TxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Nama_Serv_TxtFocusLost
        if(Nama_Serv_Txt.getText().equals("")){
            Nama_Serv_Txt.setText("Nama Service");
            Nama_Serv_Txt.setForeground(new Color(74,96,102));
        }
    }//GEN-LAST:event_Nama_Serv_TxtFocusLost

    private void Nama_Serv_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_Serv_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama_Serv_TxtActionPerformed

    private void Harga_Serv_TxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Harga_Serv_TxtFocusGained
        if(Harga_Serv_Txt.getText().equals("Harga Service")){
            Harga_Serv_Txt.setText("");
            Harga_Serv_Txt.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_Harga_Serv_TxtFocusGained

    private void Harga_Serv_TxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Harga_Serv_TxtFocusLost
        if(Harga_Serv_Txt.getText().equals("")){
            Harga_Serv_Txt.setText("Harga Service");
            Harga_Serv_Txt.setForeground(new Color(74,96,102));
        }
    }//GEN-LAST:event_Harga_Serv_TxtFocusLost

    private void Harga_Serv_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Harga_Serv_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Harga_Serv_TxtActionPerformed

    private void btnAddNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseEntered
        btnAddNew.setBackground(new Color(62,254 ,238));
    }//GEN-LAST:event_btnAddNewMouseEntered

    private void btnAddNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseExited
        btnAddNew.setBackground(new Color(11,203,187));
    }//GEN-LAST:event_btnAddNewMouseExited

    private void btnAddNewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMousePressed
        btnAddNew.setBackground(new Color(0,178,162));
    }//GEN-LAST:event_btnAddNewMousePressed

    private void btnAddNewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseReleased
        btnAddNew.setBackground(new Color(11,203,187));
    }//GEN-LAST:event_btnAddNewMouseReleased

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        
        this.setLocation(kordinatX-mousepX, kordinatY-mousepY);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tambah_Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tambah_Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tambah_Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tambah_Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tambah_Service().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close_window;
    private javax.swing.JTextField Harga_Serv_Txt;
    private javax.swing.JLabel Label_Harga;
    private javax.swing.JLabel Label_NamaServ;
    private javax.swing.JLabel Label_tambah_service;
    private javax.swing.JLabel Logo_Service;
    private javax.swing.JLabel Minimize_window;
    private javax.swing.JTextField Nama_Serv_Txt;
    private javax.swing.JLabel btnAddNew;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
