/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import Function.Customer;
import Function.MysqlCon;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.sql.DataSource;
import javax.swing.JOptionPane;
/**
 *
 * @author muham
 */
public class Tambah_Customer extends javax.swing.JDialog {
    int mousepX;
    int mousepY;
    public static Customer input = new Customer("", "","");

    /**
     * Creates new form Tambah_Cust
     */
    public Tambah_Customer(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    public static Customer getInput(){
        return input;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Close_window = new javax.swing.JLabel();
        Label_NamaCust = new javax.swing.JLabel();
        Nama_Cust_Txt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Label_NoHp = new javax.swing.JLabel();
        No_Handphone_Txt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnAddNew = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(48, 70, 76));

        jPanel2.setBackground(new java.awt.Color(139, 104, 89));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_add_user_group_woman_man_30px_1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TAMBAH CUSTOMER");

        Close_window.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close_window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_close_window_30px_2.png"))); // NOI18N
        Close_window.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_windowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(Close_window))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Close_window, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Label_NamaCust.setForeground(new java.awt.Color(255, 255, 255));
        Label_NamaCust.setText("Nama Customer :");

        Nama_Cust_Txt.setBackground(new java.awt.Color(48, 70, 76));
        Nama_Cust_Txt.setForeground(new java.awt.Color(74, 96, 102));
        Nama_Cust_Txt.setText("Nama Customer");
        Nama_Cust_Txt.setBorder(null);
        Nama_Cust_Txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Nama_Cust_TxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Nama_Cust_TxtFocusLost(evt);
            }
        });
        Nama_Cust_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_Cust_TxtActionPerformed(evt);
            }
        });

        Label_NoHp.setForeground(new java.awt.Color(255, 255, 255));
        Label_NoHp.setText("No Handphone :");

        No_Handphone_Txt.setBackground(new java.awt.Color(48, 70, 76));
        No_Handphone_Txt.setForeground(new java.awt.Color(74, 96, 102));
        No_Handphone_Txt.setText("No Handphone");
        No_Handphone_Txt.setBorder(null);
        No_Handphone_Txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                No_Handphone_TxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                No_Handphone_TxtFocusLost(evt);
            }
        });
        No_Handphone_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_Handphone_TxtActionPerformed(evt);
            }
        });

        btnAddNew.setBackground(new java.awt.Color(11, 203, 187));
        btnAddNew.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddNew.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_add_to_cloud_20px.png"))); // NOI18N
        btnAddNew.setText("Add New");
        btnAddNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAddNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddNew.setOpaque(true);
        btnAddNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddNewMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddNewMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddNewMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Label_NamaCust)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Nama_Cust_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Label_NoHp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(No_Handphone_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label_NamaCust)
                        .addComponent(Nama_Cust_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label_NoHp)
                        .addComponent(No_Handphone_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(109, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Close_windowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_windowMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Close_windowMouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();

        this.setLocation(kordinatX-mousepX, kordinatY-mousepY);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void Nama_Cust_TxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Nama_Cust_TxtFocusGained
        if(Nama_Cust_Txt.getText().equals("Nama Customer")){
            Nama_Cust_Txt.setText("");
            Nama_Cust_Txt.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_Nama_Cust_TxtFocusGained

    private void Nama_Cust_TxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Nama_Cust_TxtFocusLost
        if(Nama_Cust_Txt.getText().equals("")){
            Nama_Cust_Txt.setText("Nama Customer");
            Nama_Cust_Txt.setForeground(new Color(74,96,102));
        }
    }//GEN-LAST:event_Nama_Cust_TxtFocusLost

    private void Nama_Cust_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_Cust_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama_Cust_TxtActionPerformed

    private void No_Handphone_TxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_No_Handphone_TxtFocusGained
        if(No_Handphone_Txt.getText().equals("No Handphone")){
            No_Handphone_Txt.setText("");
            No_Handphone_Txt.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_No_Handphone_TxtFocusGained

    private void No_Handphone_TxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_No_Handphone_TxtFocusLost
        if(No_Handphone_Txt.getText().equals("")){
            No_Handphone_Txt.setText("No Handphone");
            No_Handphone_Txt.setForeground(new Color(74,96,102));
        }
    }//GEN-LAST:event_No_Handphone_TxtFocusLost

    private void No_Handphone_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_Handphone_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_No_Handphone_TxtActionPerformed

    private void btnAddNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseClicked
        // TODO add your handling code here:
       input = new Customer("", Nama_Cust_Txt.getText(), No_Handphone_Txt.getText());
        dispose();
    }//GEN-LAST:event_btnAddNewMouseClicked

    private void btnAddNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseEntered
        btnAddNew.setBackground(new Color(62,254 ,238));
    }//GEN-LAST:event_btnAddNewMouseEntered

    private void btnAddNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseExited
        btnAddNew.setBackground(new Color(11,203,187));
    }//GEN-LAST:event_btnAddNewMouseExited

    private void btnAddNewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMousePressed
        btnAddNew.setBackground(new Color(0,178,162));
    }//GEN-LAST:event_btnAddNewMousePressed

    private void btnAddNewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseReleased
        btnAddNew.setBackground(new Color(11,203,187));
    }//GEN-LAST:event_btnAddNewMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tambah_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tambah_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tambah_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tambah_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
           
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close_window;
    private javax.swing.JLabel Label_NamaCust;
    private javax.swing.JLabel Label_NoHp;
    private javax.swing.JTextField Nama_Cust_Txt;
    private javax.swing.JTextField No_Handphone_Txt;
    private javax.swing.JLabel btnAddNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
