/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;

/**
 *
 * @author muham
 */
public class Tampil_Service extends javax.swing.JFrame {

    /**
     * Creates new form Tampil_Serve
     */
    public Tampil_Service() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ICON_data_service = new javax.swing.JLabel();
        Panel_atas = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        Label_Service = new javax.swing.JLabel();
        ICON_service = new javax.swing.JLabel();
        Table = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Pembatas = new javax.swing.JLabel();
        Ubah = new javax.swing.JLabel();
        Tambah = new javax.swing.JLabel();
        Icon_ubah = new javax.swing.JLabel();
        Icon_tambah = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Jenis_service = new javax.swing.JLabel();
        Harga = new javax.swing.JLabel();
        titik_nama = new javax.swing.JLabel();
        titik_harga = new javax.swing.JLabel();
        titik_jenis_service = new javax.swing.JLabel();
        txt_jenis_service = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        ICON_crud = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        ICON_data_service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon_tampil_service/Icon_data_service.png"))); // NOI18N
        ICON_data_service.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_atas.setBackground(new java.awt.Color(111, 104, 102));

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon_tampil_service/Close.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon_tampil_service/Minimize.png"))); // NOI18N
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });

        Label_Service.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Label_Service.setForeground(new java.awt.Color(129, 178, 154));
        Label_Service.setText("Service");

        ICON_service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon_tampil_service/Service.png"))); // NOI18N

        javax.swing.GroupLayout Panel_atasLayout = new javax.swing.GroupLayout(Panel_atas);
        Panel_atas.setLayout(Panel_atasLayout);
        Panel_atasLayout.setHorizontalGroup(
            Panel_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_atasLayout.createSequentialGroup()
                .addComponent(ICON_service, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Service, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Close)
                .addContainerGap())
        );
        Panel_atasLayout.setVerticalGroup(
            Panel_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Minimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Label_Service, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ICON_service, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No.", "Jenis Service", "Harga"
            }
        ));
        Table.setViewportView(jTable1);

        Pembatas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon_tampil_service/Pembatas.png"))); // NOI18N

        Ubah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ubah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ubah.setText("Tambah");

        Tambah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Tambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tambah.setText("Ubah");

        Icon_ubah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon_tampil_service/Tambah.png"))); // NOI18N

        Icon_tambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon_tampil_service/Edit_Folder.png"))); // NOI18N

        Nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nama.setText("ID Service");

        Jenis_service.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jenis_service.setText("Jenis Service");

        Harga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Harga.setText("Harga");

        titik_nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titik_nama.setText(":");

        titik_harga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titik_harga.setText(":");

        titik_jenis_service.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titik_jenis_service.setText(":");

        txt_jenis_service.setBackground(new java.awt.Color(244, 241, 222));
        txt_jenis_service.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_jenis_service.setForeground(new java.awt.Color(142, 139, 120));
        txt_jenis_service.setText("Masukkan Jenis Service");
        txt_jenis_service.setBorder(null);
        txt_jenis_service.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_jenis_serviceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_jenis_serviceFocusLost(evt);
            }
        });

        txt_harga.setBackground(new java.awt.Color(244, 241, 222));
        txt_harga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_harga.setForeground(new java.awt.Color(142, 139, 120));
        txt_harga.setText("Masukkan Harga");
        txt_harga.setBorder(null);
        txt_harga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_hargaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_hargaFocusLost(evt);
            }
        });

        txt_nama.setEditable(false);
        txt_nama.setBackground(new java.awt.Color(244, 241, 222));
        txt_nama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nama.setForeground(new java.awt.Color(142, 139, 120));
        txt_nama.setText("Masukkan ID Service");
        txt_nama.setBorder(null);
        txt_nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_namaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_namaFocusLost(evt);
            }
        });

        ICON_crud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ICON_crud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon_tampil_service/Icon_CRUD.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Panel_atas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(Table, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(Pembatas, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(140, 140, 140)
                                    .addComponent(titik_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(160, 160, 160)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(Jenis_service)
                                    .addGap(20, 20, 20)
                                    .addComponent(titik_jenis_service, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(140, 140, 140)
                                    .addComponent(titik_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(160, 160, 160)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(160, 160, 160)
                                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(160, 160, 160)
                                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(160, 160, 160)
                                    .addComponent(txt_jenis_service, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(160, 160, 160)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(Icon_tambah))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(Icon_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ICON_crud, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Panel_atas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(Table, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(Pembatas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(titik_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(Jenis_service, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(titik_jenis_service, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addComponent(titik_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(txt_jenis_service, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(Icon_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(Icon_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ICON_crud))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CloseMouseClicked

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(Tampil_Service.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void txt_jenis_serviceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_jenis_serviceFocusGained
        // TODO add your handling code here:
        if(txt_jenis_service.getText().equals("Masukkan Jenis Service")){
            txt_jenis_service.setText("");
            txt_jenis_service.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txt_jenis_serviceFocusGained

    private void txt_jenis_serviceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_jenis_serviceFocusLost
        // TODO add your handling code here:
        if(txt_jenis_service.getText().equals("")){
            txt_jenis_service.setText("Masukkan Jenis Service");
            txt_jenis_service.setForeground(new Color(142,139,120));
        }
    }//GEN-LAST:event_txt_jenis_serviceFocusLost

    private void txt_hargaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_hargaFocusGained
        // TODO add your handling code here:
        if(txt_harga.getText().equals("Masukkan Harga")){
            txt_harga.setText("");
            txt_harga.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txt_hargaFocusGained

    private void txt_hargaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_hargaFocusLost
        // TODO add your handling code here:
        if(txt_harga.getText().equals("")){
            txt_harga.setText("Masukkan Harga");
            txt_harga.setForeground(new Color(142,139,120));
        }
    }//GEN-LAST:event_txt_hargaFocusLost

    private void txt_namaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_namaFocusGained
        // TODO add your handling code here:
        if(txt_nama.getText().equals("Masukkan ID Service")){
            txt_nama.setText("");
            txt_nama.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txt_namaFocusGained

    private void txt_namaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_namaFocusLost
        // TODO add your handling code here:
        if(txt_nama.getText().equals("")){
            txt_nama.setText("Masukkan ID Service");
            txt_nama.setForeground(new Color(142,139,120));
        }
    }//GEN-LAST:event_txt_namaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampil_Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampil_Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampil_Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampil_Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampil_Service().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Harga;
    private javax.swing.JLabel ICON_crud;
    private javax.swing.JLabel ICON_data_service;
    private javax.swing.JLabel ICON_service;
    private javax.swing.JLabel Icon_tambah;
    private javax.swing.JLabel Icon_ubah;
    private javax.swing.JLabel Jenis_service;
    private javax.swing.JLabel Label_Service;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Nama;
    private javax.swing.JPanel Panel_atas;
    private javax.swing.JLabel Pembatas;
    private javax.swing.JScrollPane Table;
    private javax.swing.JLabel Tambah;
    private javax.swing.JLabel Ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel titik_harga;
    private javax.swing.JLabel titik_jenis_service;
    private javax.swing.JLabel titik_nama;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jenis_service;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
}
