/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Function.Customer;
import Function.MysqlCon;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.sql.DataSource;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class Tampil_Customer extends javax.swing.JFrame {
    private final static DataSource ds = MysqlCon.getDataSource();
    private final static Object[] columnNames = new Object[]{"No", "Nama Customer", "No handphone"};
    /**
     * Creates new form Tampil_Customer
     */
    int mousepX;
    int mousepY;
    public Tampil_Customer() {
        initComponents();
        loadCustomer();
    }
    
    private void loadCustomer(){
        String loadCustomerSQL = "SELECT * FROM cust";
        try(
                Connection con = ds.getConnection();
                PreparedStatement statement = con.prepareStatement(loadCustomerSQL);
                ResultSet rs = statement.executeQuery()
        ){
            DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0){
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            while (rs.next()){
                tableModel.addRow(new Object[]{
                        rs.getString("id_cust"),
                        rs.getString("nama"),
                        rs.getString("nohp")
                });
            }
            tablecust.setModel(tableModel);
        }catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane,
                    "Koneksi ke tabel di database gagal",
                    "Koneksi Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void fillField(){
        DefaultTableModel tableModel = (DefaultTableModel) tablecust.getModel();
        int selectedRow = tablecust.getSelectedRow();
        Id_Cust_Txt.setText((String) tableModel.getValueAt(selectedRow, 0));
        Nama_Cust_Txt.setText((String) tableModel.getValueAt(selectedRow, 1));
        No_Handphone_Txt.setText((String) tableModel.getValueAt(selectedRow, 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Logo_TC = new javax.swing.JLabel();
        Logo_Cust = new javax.swing.JLabel();
        Close_window = new javax.swing.JLabel();
        Minimize_window = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablecust = new javax.swing.JTable();
        btnEdit = new javax.swing.JLabel();
        btnAddNew = new javax.swing.JLabel();
        Label_IDCust = new javax.swing.JLabel();
        Id_Cust_Txt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Label_NamaCust = new javax.swing.JLabel();
        Nama_Cust_Txt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Label_NoHp = new javax.swing.JLabel();
        No_Handphone_Txt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(48, 70, 76));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 40));

        jPanel2.setBackground(new java.awt.Color(139, 104, 89));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        Logo_TC.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Logo_TC.setForeground(new java.awt.Color(255, 255, 255));
        Logo_TC.setText("TAMPIL CUSTOMER");

        Logo_Cust.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo_Cust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_customer_insight_30px.png"))); // NOI18N

        Close_window.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close_window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_close_window_30px_2.png"))); // NOI18N
        Close_window.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_windowMouseClicked(evt);
            }
        });

        Minimize_window.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimize_window.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_minimize_window_30px_5.png"))); // NOI18N
        Minimize_window.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Minimize_windowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Logo_Cust, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Logo_TC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Minimize_window)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Close_window))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo_TC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Logo_Cust, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(Minimize_window, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Close_window, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tablecust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No ", "Nama", "No Handphone"
            }
        ));
        tablecust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecustMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablecust);

        btnEdit.setBackground(new java.awt.Color(20, 150, 3));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_edit_property_20px_1.png"))); // NOI18N
        btnEdit.setText(" Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setOpaque(true);
        btnEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnEditFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnEditFocusLost(evt);
            }
        });
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditMouseReleased(evt);
            }
        });

        btnAddNew.setBackground(new java.awt.Color(11, 203, 187));
        btnAddNew.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddNew.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Icon/icons8_add_to_cloud_20px.png"))); // NOI18N
        btnAddNew.setText("Add New");
        btnAddNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAddNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddNew.setOpaque(true);
        btnAddNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddNewMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddNewMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAddNewMouseReleased(evt);
            }
        });

        Label_IDCust.setForeground(new java.awt.Color(255, 255, 255));
        Label_IDCust.setText("ID Customer :");

        Id_Cust_Txt.setEditable(false);
        Id_Cust_Txt.setBackground(new java.awt.Color(48, 70, 76));
        Id_Cust_Txt.setForeground(new java.awt.Color(255, 255, 255));
        Id_Cust_Txt.setText("ID Customer");
        Id_Cust_Txt.setBorder(null);
        Id_Cust_Txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Id_Cust_TxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Id_Cust_TxtFocusLost(evt);
            }
        });

        Label_NamaCust.setForeground(new java.awt.Color(255, 255, 255));
        Label_NamaCust.setText("Nama Customer :");

        Nama_Cust_Txt.setBackground(new java.awt.Color(48, 70, 76));
        Nama_Cust_Txt.setForeground(new java.awt.Color(255, 255, 255));
        Nama_Cust_Txt.setText("Nama Customer");
        Nama_Cust_Txt.setBorder(null);
        Nama_Cust_Txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Nama_Cust_TxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Nama_Cust_TxtFocusLost(evt);
            }
        });
        Nama_Cust_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_Cust_TxtActionPerformed(evt);
            }
        });

        Label_NoHp.setForeground(new java.awt.Color(255, 255, 255));
        Label_NoHp.setText("No Handphone :");

        No_Handphone_Txt.setBackground(new java.awt.Color(48, 70, 76));
        No_Handphone_Txt.setForeground(new java.awt.Color(255, 255, 255));
        No_Handphone_Txt.setText("No Handphone");
        No_Handphone_Txt.setBorder(null);
        No_Handphone_Txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                No_Handphone_TxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                No_Handphone_TxtFocusLost(evt);
            }
        });
        No_Handphone_Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_Handphone_TxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_NamaCust)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Nama_Cust_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_IDCust)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1)
                                .addComponent(Id_Cust_Txt)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_NoHp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(No_Handphone_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(221, 221, 221))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id_Cust_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_IDCust))
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_NamaCust)
                    .addComponent(Nama_Cust_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_NoHp)
                    .addComponent(No_Handphone_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void No_Handphone_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_Handphone_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_No_Handphone_TxtActionPerformed

    private void No_Handphone_TxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_No_Handphone_TxtFocusLost
        if(No_Handphone_Txt.getText().equals("")){
            No_Handphone_Txt.setText("No Handphone");
            No_Handphone_Txt.setForeground(new Color(74,96,102));
        }
    }//GEN-LAST:event_No_Handphone_TxtFocusLost

    private void No_Handphone_TxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_No_Handphone_TxtFocusGained
        if(No_Handphone_Txt.getText().equals("No Handphone")){
            No_Handphone_Txt.setText("");
            No_Handphone_Txt.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_No_Handphone_TxtFocusGained

    private void Nama_Cust_TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_Cust_TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama_Cust_TxtActionPerformed

    private void Nama_Cust_TxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Nama_Cust_TxtFocusLost
        if(Nama_Cust_Txt.getText().equals("")){
            Nama_Cust_Txt.setText("Nama Customer");
            Nama_Cust_Txt.setForeground(new Color(74,96,102));
        }
    }//GEN-LAST:event_Nama_Cust_TxtFocusLost

    private void Nama_Cust_TxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Nama_Cust_TxtFocusGained
        if(Nama_Cust_Txt.getText().equals("Nama Customer")){
            Nama_Cust_Txt.setText("");
            Nama_Cust_Txt.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_Nama_Cust_TxtFocusGained

    private void Id_Cust_TxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Id_Cust_TxtFocusLost
        if(Id_Cust_Txt.getText().equals("")){
            Id_Cust_Txt.setText("ID Customer");
            Id_Cust_Txt.setForeground(new Color(74,96,102));
        }
    }//GEN-LAST:event_Id_Cust_TxtFocusLost

    private void Id_Cust_TxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Id_Cust_TxtFocusGained
        if(Id_Cust_Txt.getText().equals("ID Customer")){
            Id_Cust_Txt.setText("");
            Id_Cust_Txt.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_Id_Cust_TxtFocusGained

    private void btnAddNewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseReleased
        btnAddNew.setBackground(new Color(11,203,187));
    }//GEN-LAST:event_btnAddNewMouseReleased

    private void btnAddNewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMousePressed
        btnAddNew.setBackground(new Color(0,178,162));
    }//GEN-LAST:event_btnAddNewMousePressed

    private void btnAddNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseExited
        btnAddNew.setBackground(new Color(11,203,187));
    }//GEN-LAST:event_btnAddNewMouseExited

    private void btnAddNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseEntered
        btnAddNew.setBackground(new Color(62,254 ,238));
    }//GEN-LAST:event_btnAddNewMouseEntered

    private void btnAddNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewMouseClicked
        // TODO add your handling code here:
        new Tambah_Customer(this).setVisible(true);
        Customer customer = Tambah_Customer.getInput();
        if(!customer.getNamaCustomer().equals("")||!customer.getNoHandphone().equals("")){
            String tambahCustomerSQL = "INSERT INTO cust(nama, nohp) VALUES(?,?)";
            try (Connection con = ds.getConnection();
                PreparedStatement statement = con.prepareStatement(tambahCustomerSQL)){
                statement.setString(1, customer.getNamaCustomer());
                statement.setString(2, customer.getNoHandphone());
                statement.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Berhasil Tambah");
            }catch (SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane,
                    "Penambahan Service Gagal\nKode Error SQL = "+e.getSQLState(),
                    "Aksi Gagal", JOptionPane.ERROR_MESSAGE);
            }
            loadCustomer();
        }
    }//GEN-LAST:event_btnAddNewMouseClicked

    private void btnEditMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseReleased
        btnEdit.setBackground(new Color(20,150,3));
    }//GEN-LAST:event_btnEditMouseReleased

    private void btnEditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMousePressed
        btnEdit.setBackground(new Color(0,125,0));
    }//GEN-LAST:event_btnEditMousePressed

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        btnEdit.setBackground(new Color(20,150,3));
    }//GEN-LAST:event_btnEditMouseExited

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        btnEdit.setBackground(new Color(46,176,29));
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        String editServisSQL = "UPDATE cust SET nama = ? , nohp = ? WHERE id_cust = ?";
        try (
            Connection con = ds.getConnection();
            PreparedStatement statement = con.prepareStatement(editServisSQL)
        ){
            statement.setString(3, Id_Cust_Txt.getText());
            statement.setString(1, Nama_Cust_Txt.getText());
            statement.setString(2, No_Handphone_Txt.getText());
            statement.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
            Id_Cust_Txt.setText("");
            Nama_Cust_Txt.setText("");
            No_Handphone_Txt.setText("");
        }catch (SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane,
                "Pengubahan Customer Gagal\nKode Error SQL = "+ ex.getSQLState(),
                "Aksi Gagal", JOptionPane.ERROR_MESSAGE);
        }
        loadCustomer();
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnEditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEditFocusLost

    }//GEN-LAST:event_btnEditFocusLost

    private void btnEditFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnEditFocusGained

    }//GEN-LAST:event_btnEditFocusGained

    private void tablecustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecustMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()>1) fillField();
    }//GEN-LAST:event_tablecustMouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();

        this.setLocation(kordinatX-mousepX, kordinatY-mousepY);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void Minimize_windowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimize_windowMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_Minimize_windowMouseClicked

    private void Close_windowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_windowMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Close_windowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampil_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampil_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampil_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampil_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampil_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close_window;
    private javax.swing.JTextField Id_Cust_Txt;
    private javax.swing.JLabel Label_IDCust;
    private javax.swing.JLabel Label_NamaCust;
    private javax.swing.JLabel Label_NoHp;
    private javax.swing.JLabel Logo_Cust;
    private javax.swing.JLabel Logo_TC;
    private javax.swing.JLabel Minimize_window;
    private javax.swing.JTextField Nama_Cust_Txt;
    private javax.swing.JTextField No_Handphone_Txt;
    private javax.swing.JLabel btnAddNew;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tablecust;
    // End of variables declaration//GEN-END:variables
}
